var imageKart1 = require("./kart1.png")
var imageKart2 = require("./kart2.png")
var imageKart3 = require("./kart3.png")
var imageKart4 = require("./kart4.png")
var imageKart5 = require("./kart5.png")
var imageKart6 = require("./kart6.png")
var imageKart7 = require("./kart7.png")
var imageKart8 = require("./kart8.png")